name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # env: # Set environment variables at the job level
    #   NODE_ENV: production
    #   API_URL: https://example.com/api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript typecheck
        env: # You can also set environment variables at the step level
          TS_NODE_ENV: production
        run: npm run typecheck

      - name: Run linter
        run: npm run lint
